<a href="https://colab.research.google.com/github/sakethbachu/Resmodel/blob/main/Reporting_F1Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import torch.nn.functional as F
import torch

def metrics_f1(y_true, y_pred):

  '''
  Helper function for F1score

  Input: y_true: A binary tensor of ndim = 2
  y_pred: A binary tensor of ndim = 2 (After passing through softmax and setting of the threshold/argmax)
    
  Returns: Precision, Recall, F1 - score

  '''

  pr, rec, f1 = F1_Score(y_true, y_pred)

  print('Precision : ', pr, '\nRecall : ', rec, '\nF1-Score : ', f1)



def F1_Score(y_true, y_pred):
    '''
    Input: y_true: A binary tensor of ndim = 2
    y_pred: A binary tensor of ndim = 2 (After passing through softmax and setting of the threshold/argmax)
    
    Returns: F1 - score
    
    '''
    epsilon = 1e-7

    if type(y_pred) and type(y_true) != torch.Tensor:

      y_true = torch.tensor(y_true)
      y_pred = torch.tensor(y_pred)


    y_true = torch.flatten(y_true).to(torch.float32)
    y_pred = torch.flatten(y_pred).to(torch.float32)
        
    # assert y_true.ndim == 1

    # assert y_pred.ndim == 1 

    # print(y_true)
    # print(y_pred)
    
    tp = (y_true * y_pred).sum(dim=0).to(torch.float32)
    tn = ((1 - y_true) * (1 - y_pred)).sum(dim=0).to(torch.float32)
    fp = ((1 - y_true) * y_pred).sum(dim=0).to(torch.float32)
    fn = (y_true * (1 - y_pred)).sum(dim=0).to(torch.float32)

    precision = tp / (tp + fp + epsilon)
    recall = tp / (tp + fn + epsilon)

    f1 = 2* (precision*recall) / (precision + recall + epsilon)

    return precision, recall, f1

In [116]:
from sklearn.metrics import f1_score


#Already flattened
y_true = [0, 1, 0, 0, 1, 1, 1, 0]

y_pred = [0, 1, 0, 0, 0, 1, 0, 0]


skl = f1_score(y_true, y_pred, pos_label=1, average='binary')


metrics_f1(y_true, y_pred)

print('F1-Score from sklearn: ', skl)

Precision :  tensor(1.) 
Recall :  tensor(0.5000) 
F1-Score :  tensor(0.6667)
F1-Score from sklearn:  0.6666666666666666


In [113]:
from sklearn.metrics import f1_score


#Already flattened
y_true = [[0, 1, 0],
          [0, 1, 1],
          [1, 0, 0]]

y_pred = [[0, 1, 0],
         [0, 0, 1], 
         [0, 0, 0]]

skl = f1_score(y_true, y_pred, pos_label=1, average='micro')

metrics_f1(y_true, y_pred)

print('F1-Score from sklearn: ', skl)

Precision :  tensor(1.) 
Recall :  tensor(0.5000) 
F1-Score :  tensor(0.6667)
F1-Score from sklearn:  0.6666666666666666


In [87]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
a

tensor([[0.9752, 0.7165, 0.0779],
        [0.4521, 0.7870, 0.1850]])

In [88]:
b

tensor([[0.3736, 0.7412, 0.4793],
        [0.8990, 0.6052, 0.9823]])

In [96]:
d = metrics_f1(a, b)

tensor([0.9752, 0.7165, 0.0779, 0.4521, 0.7870, 0.1850])
tensor([0.3736, 0.7412, 0.4793, 0.8990, 0.6052, 0.9823])
Precision :  tensor(0.4894) 
Recall :  tensor(0.6254) 
F1-Score :  tensor(0.5491)


In [32]:
t = torch.tensor([[1, 0, 0, 1],
                  [0, 1, 1, 1]])
b = torch.tensor([[1, 1, 0, 0],
                  [1, 1, 1, 1]])